#!/usr/bin/env python3
"""Generate code from the sheets. The sheets are the source of truth: edit them, not the output.

Writes:
  ats_plugin/generated/sheet_data.h                  (C++: state struct, channel/event hooks, constants, encoders)
  beamng_mod/lua/ge/extensions/shadowRig/sheetData.lua (Lua: constants, obstacles, rigs, world, protocol)
  melty.json                                          (Melty install recipe, '*' where the version goes)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
S = {json.loads(p.read_text())["sheet"]: json.loads(p.read_text()) for p in (ROOT / "sheets").glob("*.json")}
rows = lambda name: S[name]["rows"]

CPP_TYPE = {"float": "float", "bool": "bool", "fvector": "scs_value_fvector_t", "string": "std::string", "u32": "unsigned"}
STORE = {"float": "store_float", "bool": "store_bool", "fvector": "store_fvector"}
SCS_TYPE = {"float": "SCS_VALUE_TYPE_float", "bool": "SCS_VALUE_TYPE_bool", "fvector": "SCS_VALUE_TYPE_fvector"}
EV_GET = {"string": "a->value.value_string.value ? a->value.value_string.value : \"\"",
          "float": "a->value.value_float.value", "u32": "a->value.value_u32.value"}
CHECK = {"string": "SCS_VALUE_TYPE_string", "float": "SCS_VALUE_TYPE_float", "u32": "SCS_VALUE_TYPE_u32"}


def c_str(s):
    return json.dumps(s)


def gen_cpp():
    out = ["// GENERATED by tools/gen.py from sheets/*.json - do not edit by hand.",
           "#pragma once", "#include <string>", "#include <cstring>", "#include <cstdio>",
           '#include "scssdk_telemetry.h"', "", "namespace sheet {", ""]
    # constants (crash_rules)
    out.append("// crash_rules")
    for r in rows("crash_rules"):
        out.append(f"constexpr double {r['id']} = {r['value']};  // {r['unit']}: {r['meaning']}")
    out.append("struct Rules {")
    for r in rows("crash_rules"):
        out.append(f"    static constexpr double {r['id']} = sheet::{r['id']};")
    out.append("};")
    out.append("")
    # state struct (ats_channels + ats_events): one field per row
    out.append("struct State {")
    for r in rows("ats_channels"):
        init = "{}" if r["value_type"] == "fvector" else ("false" if r["value_type"] == "bool" else "0.0f")
        out.append(f"    {CPP_TYPE[r['value_type']]} {r['id']} = {init};  // {r['sdk_name']}")
    for r in rows("ats_events"):
        init = '""' if r["value_type"] == "string" else "0"
        out.append(f"    {CPP_TYPE[r['value_type']]} {r['id']} = {init};  // {r['event_id']}/{r['attribute']}")
    out.append("};\n")
    # computed values (protocol computed:* sources)
    comp = sorted({r["source"].split(":", 1)[1] for r in rows("protocol") if r["source"].startswith("computed:")})
    comp_types = {}
    for r in rows("protocol"):
        if r["source"].startswith("computed:"):
            comp_types[r["source"].split(":", 1)[1]] = r["json_type"]
    out.append("struct Computed {")
    for c in comp:
        t = {"number": "double", "bool": "bool", "string": "std::string"}[comp_types[c]]
        init = {"double": "0", "bool": "false", "std::string": '""'}[t]
        out.append(f"    {t} {c} = {init};")
    out.append("};\n")
    # channel store callbacks + registration: one line per ats_channels row
    out += [
        "inline SCSAPI_VOID store_float(const scs_string_t, const scs_u32_t, const scs_value_t *v, const scs_context_t ctx) {",
        "    *static_cast<float *>(ctx) = v ? v->value_float.value : 0.0f; }",
        "inline SCSAPI_VOID store_bool(const scs_string_t, const scs_u32_t, const scs_value_t *v, const scs_context_t ctx) {",
        "    *static_cast<bool *>(ctx) = v ? (v->value_bool.value != 0) : false; }",
        "inline SCSAPI_VOID store_fvector(const scs_string_t, const scs_u32_t, const scs_value_t *v, const scs_context_t ctx) {",
        "    scs_value_fvector_t *d = static_cast<scs_value_fvector_t *>(ctx); if (v) *d = v->value_fvector; else d->x = d->y = d->z = 0; }",
        "",
        "// Returns the number of channels that failed to register (missing in this game version).",
        "inline int register_channels(const scs_telemetry_init_params_v101_t *p, State &s) {",
        "    int failed = 0;"]
    for r in rows("ats_channels"):
        idx = "SCS_U32_NIL" if r["index"] == -1 else str(r["index"])
        out.append(f"    if (p->register_for_channel({c_str(r['sdk_name'])}, {idx}, {SCS_TYPE[r['value_type']]}, "
                   f"SCS_TELEMETRY_CHANNEL_FLAG_no_value, {STORE[r['value_type']]}, &s.{r['id']}) != SCS_RESULT_ok) ++failed;")
    out += ["    return failed;", "}", ""]
    # configuration / gameplay attribute pickup: one branch per ats_events row
    for kind in ("configuration", "gameplay"):
        out.append(f"inline void apply_{kind}(const char *event_id, const scs_named_value_t *attrs, State &s) {{")
        evs = [r for r in rows("ats_events") if r["event"] == kind]
        for eid in sorted({r["event_id"] for r in evs}):
            out.append(f"    if (std::strcmp(event_id, {c_str(eid)}) == 0) {{")
            for r in [r for r in evs if r["event_id"] == eid]:
                reset = '""' if r["value_type"] == "string" else "0"
                out.append(f"        s.{r['id']} = {reset};")
            out.append("        for (const scs_named_value_t *a = attrs; a && a->name; ++a) {")
            for r in [r for r in evs if r["event_id"] == eid]:
                out.append(f"            if (std::strcmp(a->name, {c_str(r['attribute'])}) == 0 && a->value.type == {CHECK[r['value_type']]}) "
                           f"s.{r['id']} = {EV_GET[r['value_type']]};")
            out += ["        }", "    }"]
        out += ["}", ""]
    # encoders: one field write per protocol row
    out += ["inline void put_str(std::string &o, const std::string &v) {",
            "    o += '\"'; for (char c : v) { if (c == '\"' || c == '\\\\') { o += '\\\\'; o += c; } else if ((unsigned char)c >= 0x20) o += c; } o += '\"'; }",
            "inline void put_num(std::string &o, double v) { char b[32]; std::snprintf(b, sizeof b, \"%.4f\", v); o += b; }",
            "inline void put_bool(std::string &o, bool v) { o += v ? \"true\" : \"false\"; }", ""]
    for msg in sorted({r["msg"] for r in rows("protocol")}):
        out.append(f"inline std::string encode_{msg}(const State &s, const Computed &c) {{")
        out.append("    (void)s; (void)c;")
        out.append(f"    std::string o = \"{{\\\"t\\\":\\\"{msg}\\\"\";")
        for r in [r for r in rows("protocol") if r["msg"] == msg]:
            src = r["source"]
            expr = f"c.{src.split(':', 1)[1]}" if src.startswith("computed:") else f"s.{src}"
            put = {"number": "put_num", "bool": "put_bool", "string": "put_str"}[r["json_type"]]
            out.append(f"    o += \",\\\"{r['field']}\\\":\"; {put}(o, {expr});  // {r['unit']}")
        out += ["    o += '}';", "    return o;", "}", ""]
    out.append("}  // namespace sheet")
    return "\n".join(out) + "\n"


def lua_val(v, ind=""):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, dict):
        inner = ", ".join(f"{k} = {lua_val(x)}" if re.match(r"^[A-Za-z_]\w*$", k) else f"[{json.dumps(k)}] = {lua_val(x)}"
                          for k, x in v.items())
        return "{" + inner + "}"
    if isinstance(v, list):
        return "{" + ", ".join(lua_val(x) for x in v) + "}"
    raise TypeError(v)


def gen_lua():
    out = ["-- GENERATED by tools/gen.py from sheets/*.json - do not edit by hand.", "local M = {}", ""]
    out.append("M.rules = {")
    for r in rows("crash_rules"):
        out.append(f"  {r['id']} = {lua_val(r['value'])},  -- {r['unit']}")
    out.append("}\n")
    out.append("M.world = {")
    for r in rows("world"):
        out.append(f"  {r['id']} = {lua_val(r['value'])},")
    out.append("}\n")
    out.append("M.obstacles = {  -- sorted by min_kmh")
    for r in sorted(rows("obstacles"), key=lambda r: r["min_kmh"]):
        out.append("  " + lua_val({k: r[k] for k in ("id", "min_kmh", "max_kmh", "beamng_model", "beamng_config", "ahead_m", "label")}) + ",")
    out.append("}\n")
    out.append("M.rigs = {")
    for r in rows("rigs"):
        out.append(f"  {r['id']} = " + lua_val({k: r[k] for k in ("role", "beamng_model", "beamng_config", "spawn_offset_m", "needs")}) + ",")
    out.append("}\n")
    out.append("M.protocol = {")
    for msg in sorted({r["msg"] for r in rows("protocol")}):
        fields = {r["field"]: r["json_type"] for r in rows("protocol") if r["msg"] == msg}
        out.append(f"  {msg} = {lua_val(fields)},")
    out.append("}\n")
    out.append("M.hooks = {" + ", ".join(json.dumps(r["id"]) for r in rows("beamng_hooks")) + "}")
    out += ["", "return M"]
    return "\n".join(out) + "\n"


def gen_recipe():
    inst = rows("install")
    pick = lambda kind: [r["value"] for r in inst if r["kind"] == kind]
    comps = []
    for c in pick("component"):
        c = dict(c)
        c["fileName"] = c["fileName"].replace("{version}", "*")
        comps.append(c)
    recipe = {
        "schemaVersion": 1,
        "mode": "installed",
        "games": pick("game"),
        "components": comps,
        "requirements": [],
        "mappings": pick("mapping"),
        "launch": pick("launch")[0],
        "together": pick("together"),
    }
    mp = pick("multiplayer")
    if mp:
        recipe["multiplayer"] = mp[0]
    return json.dumps(recipe, indent=2) + "\n"


def check_api():
    """Every beamng_hooks row must have exactly one function in api.lua, and nothing extra."""
    api = (ROOT / "beamng_mod/lua/ge/extensions/shadowRig/api.lua").read_text()
    have = set(re.findall(r"^function A\.(\w+)\(", api, re.M))
    want = {r["id"] for r in rows("beamng_hooks") if r["side"] in ("ge", "veh")}
    problems = [f"api.lua missing hook '{h}'" for h in sorted(want - have)]
    problems += [f"api.lua has '{h}' which is not in sheets/beamng_hooks.json" for h in sorted(have - want)]
    ext = (ROOT / "beamng_mod/lua/ge/extensions/shadowRig.lua").read_text()
    have_cb = set(re.findall(r"^M\.(on\w+) = ", ext, re.M))
    want_cb = {r["id"] for r in rows("beamng_hooks") if r["side"] == "callback"}
    problems += [f"shadowRig.lua missing callback '{h}'" for h in sorted(want_cb - have_cb)]
    problems += [f"shadowRig.lua sets '{h}' which is not in sheets/beamng_hooks.json" for h in sorted(have_cb - want_cb)]
    if not (ROOT / "beamng_mod/scripts/shadowRig/modScript.lua").exists():
        problems.append("beamng_mod/scripts/shadowRig/modScript.lua missing")
    return problems


def main():
    (ROOT / "ats_plugin/generated/sheet_data.h").write_text(gen_cpp())
    (ROOT / "beamng_mod/lua/ge/extensions/shadowRig/sheetData.lua").write_text(gen_lua())
    (ROOT / "melty.json").write_text(gen_recipe())
    problems = check_api()
    for p in problems:
        print("ERROR", p)
    print("generated: ats_plugin/generated/sheet_data.h, beamng_mod/.../sheetData.lua, melty.json")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
