-- GENERATED by tools/gen.py from sheets/*.json - do not edit by hand.
local M = {}

M.rules = {
  window_s = 0.5,  -- s
  min_speed_drop_kmh = 12.0,  -- km/h
  min_peak_g = 1.2,  -- g
  min_damage_delta = 0.004,  -- 0..1
  cooldown_s = 6.0,  -- s
  repair_drop = 0.02,  -- 0..1
  send_rate_hz = 20,  -- Hz
  udp_port = 47750,  -- port
}

M.world = {
  level_path = "/levels/west_coast_usa/main.level.json",
  obstacle_life_s = 20,
  stale_tick_s = 2,
}

M.obstacles = {  -- sorted by min_kmh
  {id = "light", min_kmh = 0, max_kmh = 35, beamng_model = "barrier", beamng_config = "default", ahead_m = 6, label = "Barrier"},
  {id = "medium", min_kmh = 35, max_kmh = 70, beamng_model = "etk800", beamng_config = "default", ahead_m = 7, label = "Parked car"},
  {id = "heavy", min_kmh = 70, max_kmh = 999, beamng_model = "blockwall", beamng_config = "default", ahead_m = 8, label = "Concrete wall"},
}

M.rigs = {
  tractor = {role = "tractor", beamng_model = "us_semi", beamng_config = "default", spawn_offset_m = 0, needs = "none"},
  trailer = {role = "trailer", beamng_model = "dryvan", beamng_config = "default", spawn_offset_m = 10, needs = "trailer_attached"},
}

M.protocol = {
  crash = {kmh = "number", g = "number", dmg = "number", why = "string"},
  repair = {wear = "number"},
  tick = {spd = "number", str = "number", thr = "number", brk = "number", trl = "bool", kg = "number", cargo = "string", brand = "string", cdmg = "number", pause = "bool"},
}

M.hooks = {"udp_open", "json_decode", "start_level", "level_loaded", "spawn_vehicle", "player_vehicle", "vehicle_pose", "delete_vehicle", "ai_traffic", "ai_speed", "couple_trailer", "add_cargo_mass", "message", "log", "onExtensionLoaded", "onExtensionUnloaded", "onUpdate", "onClientEndMission", "modScript"}

return M
